spring.application.name=gestao_eventos

spring.datasource.url = jdbc:postgresql://roundly-delighted-pilchard.data-1.use1.tembo.io:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = postgresadmin123456789
spring.jpa.hibernate.ddl-auto=update

